system "../../compiler/min-caml-0.1.0/min-caml ../../compiler/min-caml-0.1.0/test/fib"
system "../../compiler/min-caml-0.1.0/min-caml ../../compiler/min-caml-0.1.0/test/tuple"
system "../../compiler/min-caml-0.1.0/min-caml ../../compiler/min-caml-0.1.0/test/adder"
system "../../compiler/min-caml-0.1.0/min-caml ../../compiler/min-caml-0.1.0/test/float_test"
system "cp ../../compiler/min-caml-0.1.0/test/array.s ."
system "cp ../../compiler/min-caml-0.1.0/test/tuple.s ."
system "cp ../../compiler/min-caml-0.1.0/test/fib.s ."
system "cp ../../compiler/min-caml-0.1.0/test/adder.s ."
system "cp ../../compiler/min-caml-0.1.0/test/float_test.s ."
